<div class="topnav">
    <a class="active" href="#home">Home</a>
    <a href="#news">News</a>
    <a href="#contact">Contact</a>
    <div class="topnav-right">
        <a href="#search">Search</a>
        <a href="#about">About</a>
    </div>
</div>
<section class="hero">
    <div class="bg">
        <h1>Lorem ipsum dolor sit amet consectetur <br>adipisicing elit. Illum ipsam aperiam repellat officia expedita <br>fuga pariatur! Ipsum mollitia perspiciatis quis.</h1>
    </div>
</section>
</body>
</html>


<nav class="navbar navbar-expend-lg fixed-top">
    <a class="navbar-brand" href="#">Home</a>
</nav>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target='#navbarSupportedContent' aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-4">
        <li class="nav-item">
            <a class="nav-link" data-value="about" href="#">About</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-value="portfolio" href="#">Portfolio</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-value="blog" href="#">Blog</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-value="team" href="#">Team</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-value="contact" href="#">Contact</a>
        </li>
    </ul>
</div>
